language: node_js
node_js:
  - "12"

branches:
  only:
    - master

sudo: required
dist: trusty

before_script:
  - npm install -g codecov

cache:
  directories:
    — node_modules

script:
  - npm test
  - istanbul cover ./node_modules/mocha/bin/_mocha --reporter lcovonly -- -R spec

after_success:
  - codecov
